---
- name: Configure web server
  hosts: webserver
  become: true
  roles:
    - { role: base, tags: ["base"] }
    - { role: nginx, tags: ["nginx"] }
    - { role: app, tags: ["app"] }
    - { role: ssh, tags: ["ssh"] }
